
import platform, os

env = Environment()
src_cs = Split('TestCS.cc #../src/CircularStrategy.cc')
src_fd = Split('TestFD.cc #../src/FilesDep.cc')

if (platform.system() == "Linux"):
    env.Append(CPPPATH = '../include')
    env.Append(CPPFLAGS = '-Wall -Wextra -ansi -pedantic-errors -Wno-deprecated -O2')
    env.Append(LIBS = Split('boost_unit_test_framework'))

    env_cs = env.Clone()
    env_cs.Program('TestCS', src_cs)

    env_fd = env.Clone()
    env_fd.Append(LIBS = Split('boost_regex boost_filesystem'))
    env_fd.Program('TestFD', src_fd)

